# Generated by Django 6.0.1 on 2026-01-24 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='categoria',
            new_name='Categoria',
        ),
    ]
