# Generated by Django 6.0.1 on 2026-01-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_rename_categoria_produto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='')),
                ('link_destino', models.CharField(blank=True, max_length=400, null=True)),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='Categoria',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, max_length=400, upload_to=''),
        ),
    ]
