# Generated by Django 6.0.1 on 2026-01-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_banner_rename_categoria_produto_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
