# Generated by Django 6.0.1 on 2026-02-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_alter_itemestoque_cor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedido',
            table='loja_pedido',
        ),
    ]
