# Generated by Django 6.0.1 on 2026-02-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_alter_pedido_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedido',
            table='loja_pedidos',
        ),
    ]
