# Generated by Django 6.0.1 on 2026-03-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_alter_pedido_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedido',
            table=None,
        ),
    ]
